"""Blueprint pipeline: /new <key> with optional wizard + render."""

from __future__ import annotations

from decimal import Decimal, InvalidOperation
from pathlib import Path
import tempfile
import shutil
import re
import os
import subprocess
from typing import TYPE_CHECKING

from rich.panel import Panel

from solcoder.cli.blueprints import (
    load_registry,
    load_wizard_schema,
    prompt_wizard,
    resolve_registry_template_path,
)
from solcoder.cli.types import CommandResponse, CommandRouter, SlashCommand
from solcoder.cli.commands.deploy import _rpc_for_cluster
from solcoder.core import RenderOptions, TemplateError, available_templates, render_template
from solcoder.solana.constants import TOKEN_2022_PROGRAM_ID
import json

if TYPE_CHECKING:  # pragma: no cover
    from solcoder.cli.app import CLIApp


KNOWN_KEYS = {"counter", "token", "nft", "registry", "escrow"}

TOKEN_2022_PROGRAM_ARGS = ["--program-id", TOKEN_2022_PROGRAM_ID]


def _prompt_or_default(app: CLIApp, prompt: str, default: str) -> str:
    try:
        resp = app._prompt_text(f"{prompt} [{default}]")
        return resp.strip() or default
    except Exception:
        return default


def _auto_create_local_metadata(app: "CLIApp", *, name: str, symbol: str) -> str:
    """Create a minimal metadata JSON locally and return a file:// URI.

    Writes under <workspace>/.solcoder/uploads/<timestamp>/metadata.json
    """
    import json as _json
    import time as _time

    try:
        root = Path(getattr(app.session_context.metadata, "active_project", None) or Path.cwd())
    except Exception:
        root = Path.cwd()
    uploads = root / ".solcoder" / "uploads" / _time.strftime("%Y%m%d_%H%M%S")
    uploads.mkdir(parents=True, exist_ok=True)
    payload = {
        "name": name,
        "symbol": symbol,
        "description": f"Metadata for {name} (generated by SolCoder)",
        "image": "",
        "attributes": [],
    }
    out_path = uploads / "metadata.json"
    try:
        out_path.write_text(_json.dumps(payload, indent=2))
        return f"file://{out_path}"
    except Exception:
        return ""


def register(app: CLIApp, router: CommandRouter) -> None:
    """Register the /new command."""

    def handle(app: CLIApp, args: list[str]) -> CommandResponse:
        if not args:
            keys = ", ".join(sorted(KNOWN_KEYS))
            return CommandResponse(messages=[("system", f"Usage: /new <key> [--dir <path>] [--program <name>] [--author <pubkey>] [--cluster <cluster>] [--program-id <id>] [--force]\nAvailable keys: {keys}")])

        key = args[0].strip().lower()
        # Parse flags
        dest: Path | None = None
        program_name: str | None = None
        author: str | None = None
        program_id: str | None = None
        cluster: str | None = None
        force = False
        quick_mode = False
        quick_decimals: int | None = None
        quick_supply: str | None = None
        quick_meta_name: str | None = None
        quick_meta_symbol: str | None = None
        quick_meta_uri: str | None = None
        quick_meta_royalty_bps: str | None = None
        quick_meta_creators: str | None = None
        quick_meta_collection: str | None = None
        quick_meta_run: bool = False

        i = 1
        while i < len(args):
            tok = args[i]
            if tok == "--dir" and i + 1 < len(args):
                dest = Path(args[i + 1]).expanduser()
                i += 2
                continue
            if tok == "--program" and i + 1 < len(args):
                program_name = args[i + 1]
                i += 2
                continue
            if tok == "--author" and i + 1 < len(args):
                author = args[i + 1]
                i += 2
                continue
            if tok == "--program-id" and i + 1 < len(args):
                program_id = args[i + 1]
                i += 2
                continue
            if tok == "--cluster" and i + 1 < len(args):
                cluster = args[i + 1]
                i += 2
                continue
            if tok == "--force":
                force = True
                i += 1
                continue
            if tok == "--quick":
                quick_mode = True
                i += 1
                continue
            if tok == "--mode" and i + 1 < len(args):
                mode_val = args[i + 1].strip().lower()
                if mode_val == "quick":
                    quick_mode = True
                i += 2
                continue
            if tok == "--decimals" and i + 1 < len(args):
                try:
                    quick_decimals = int(args[i + 1])
                except Exception:
                    return CommandResponse(messages=[("system", "--decimals must be an integer between 0 and 9")])
                i += 2
                continue
            if tok == "--supply" and i + 1 < len(args):
                quick_supply = args[i + 1]
                i += 2
                continue
            if tok == "--meta-name" and i + 1 < len(args):
                quick_meta_name = args[i + 1]
                i += 2
                continue
            if tok == "--meta-symbol" and i + 1 < len(args):
                quick_meta_symbol = args[i + 1]
                i += 2
                continue
            if tok == "--meta-uri" and i + 1 < len(args):
                quick_meta_uri = args[i + 1]
                i += 2
                continue
            if tok == "--meta-royalty-bps" and i + 1 < len(args):
                quick_meta_royalty_bps = args[i + 1]
                i += 2
                continue
            if tok == "--meta-creators" and i + 1 < len(args):
                quick_meta_creators = args[i + 1]
                i += 2
                continue
            if tok == "--meta-collection" and i + 1 < len(args):
                quick_meta_collection = args[i + 1]
                i += 2
                continue
            if tok == "--meta-run":
                quick_meta_run = True
                i += 1
                continue
            return CommandResponse(messages=[("system", f"Unknown or misplaced argument '{tok}'.")])

        # Key mapping / selection
        templates = set(available_templates())
        registry = load_registry()
        if key not in KNOWN_KEYS:
            # Free-text: try LLM minimal selection first with strict JSON; fall back to prompt
            try:
                reg = load_registry()
                options_list = [e.key for e in reg if e.key]
                if not options_list:
                    options_list = sorted(KNOWN_KEYS)
                options_str = ", ".join(options_list)
                system = (
                    "You are a strict router. Select exactly one blueprint key from the provided list. "
                    "Respond ONLY with a minified JSON object of the form {\"key\":\"<value>\"} where <value> is one of the allowed keys."
                )
                user = (
                    f"Allowed keys: [{options_str}]\\n"
                    f"Request: {' '.join(args)}\\n"
                    "Return strictly: {\"key\":\"<one_of_allowed>\"}"
                )
                resp = app._llm.stream_chat(user, system_prompt=system, history=None)
                raw = (resp.text or "").strip()
                candidate_key: str | None = None
                # Try JSON parse first
                try:
                    obj = json.loads(raw)
                    val = obj.get("key") if isinstance(obj, dict) else None
                    if isinstance(val, str):
                        candidate_key = val.strip().lower()
                except Exception:
                    # Try to extract with a simple pattern
                    m = re.search(r'"key"\s*:\s*"([a-zA-Z0-9_-]+)"', raw)
                    if m:
                        candidate_key = m.group(1).lower()
                if candidate_key in KNOWN_KEYS:
                    key = candidate_key  # type: ignore[assignment]
                else:
                    raise ValueError("invalid llm selection JSON")
            except Exception:
                options = ", ".join(sorted(KNOWN_KEYS))
                chosen = _prompt_or_default(app, f"Select a blueprint key ({options})", "counter")
                key = chosen.strip().lower()
                if key not in KNOWN_KEYS:
                    return CommandResponse(messages=[("system", f"Invalid key '{key}'. Available: {options}")])

        # Fast path: agent or power-user requested quick mint directly via flags
        if key == "token" and quick_mode:
            if quick_decimals is None or quick_supply is None:
                return CommandResponse(messages=[("system", "Missing --decimals or --supply for quick token flow.")])
            return _spl_token_quick_flow(
                app,
                decimals_input=quick_decimals,
                supply_input=quick_supply,
                cluster_hint=cluster,
                meta_name=quick_meta_name,
                meta_symbol=quick_meta_symbol,
                meta_uri=quick_meta_uri,
                meta_royalty_bps=quick_meta_royalty_bps,
                meta_creators=quick_meta_creators,
                meta_collection=quick_meta_collection,
                meta_run=quick_meta_run,
            )

        # Wizard (load per-blueprint schema if available)
        defaults = app._default_template_metadata()
        wizard_qs = load_wizard_schema(key)
        answers: dict[str, any] = {}

        if wizard_qs:
            # seed defaults
            cfg_ctx = getattr(app, "config_context", None)
            network = None
            if cfg_ctx is not None and getattr(cfg_ctx, "config", None) is not None:
                network = getattr(cfg_ctx.config, "network", None)
            # Prefer the selected key for program_name default rather than the global default (counter)
            seed = {
                "program_name": program_name or key,
                "author_pubkey": author or defaults.get("author_pubkey", "CHANGEME"),
                "cluster": cluster or network or "devnet",
                "program_id": program_id or "replace-with-program-id",
            }
            if key == "token":
                seed.setdefault("token_mode", "quick")
                seed.setdefault("decimals", 9)
                seed.setdefault("initial_supply", "0")
            answers = prompt_wizard(app, wizard_qs, seed)
            if key == "token":
                token_mode = (answers.get("token_mode") or seed.get("token_mode", "program")).strip().lower()
                if token_mode == "quick":
                    cluster_hint = answers.get("cluster") or seed.get("cluster")
                    decimals_value = answers.get("decimals", seed.get("decimals"))
                    supply_value = answers.get("initial_supply", seed.get("initial_supply"))
                    # Also collect metadata inline to avoid a second wizard step
                    intro_lines = [
                        "[bold cyan]Quick Token Mint[/bold cyan]",
                        "Press Enter to accept the suggested value in brackets.",
                        "[dim]Leave optional fields empty to skip them.[/dim]",
                    ]
                    app.console.print(Panel.fit("\n".join(intro_lines), title="Quick Token Wizard", border_style="cyan"))
                    app.console.print()
                    app.console.print("[bold]Token configuration[/bold]")
                    default_uri = (answers.get("metadata_pointer_uri") or "").strip()
                    meta_name = app._prompt_text("Metadata Name [SolCoder Token]").strip() or "SolCoder Token"
                    meta_symbol = app._prompt_text("Metadata Symbol [SCT]").strip() or "SCT"
                    app.console.print()
                    app.console.print("[bold]Metadata[/bold]")
                    meta_uri = app._prompt_text(f"Metadata URI [{default_uri or 'auto-generate'}]").strip() or default_uri
                    if not meta_uri:
                        # Auto-generate a local metadata.json and use its file:// URI
                        meta_uri = _auto_create_local_metadata(app, name=meta_name, symbol=meta_symbol)
                    meta_royalty = app._prompt_text("Seller fee bps (optional)").strip()
                    meta_creators = app._prompt_text("Creators 'PK:BPS,...' (optional)").strip()
                    meta_collection = app._prompt_text("Collection address (optional)").strip()
                    meta_run_answer = app._prompt_text("Write metadata on-chain now? [Y/n]").strip().lower()
                    meta_run = meta_run_answer not in {"n", "no"}
                    return _spl_token_quick_flow(
                        app,
                        decimals_input=decimals_value,
                        supply_input=supply_value,
                        cluster_hint=cluster_hint,
                        meta_name=meta_name,
                        meta_symbol=meta_symbol,
                        meta_uri=meta_uri,
                        meta_royalty_bps=meta_royalty,
                        meta_creators=meta_creators,
                        meta_collection=meta_collection,
                        meta_run=meta_run,
                    )
            program_name = answers.get("program_name") or seed["program_name"]
            author = answers.get("author_pubkey") or seed["author_pubkey"]
            cluster = answers.get("cluster") or seed["cluster"]
            program_id = answers.get("program_id") or seed["program_id"]
        else:
            if program_name is None:
                # Default to the blueprint key for program name rather than the global default (counter)
                program_name = _prompt_or_default(app, "Program name", key)
            if author is None:
                author = defaults.get("author_pubkey", "CHANGEME")
            if cluster is None:
                cfg = getattr(app, "config_context", None)
                cluster = getattr(getattr(cfg, "config", None), "network", "devnet")
            if program_id is None:
                program_id = "replace-with-program-id"

        # Destination base (used both for scaffold and for workspace detection)
        base_dir = dest or Path.cwd()

        # Detect existing Anchor workspace to insert program under programs/
        def _find_anchor_root(start: Path) -> Path | None:
            try:
                cur = start.resolve()
            except Exception:
                cur = start.expanduser()
            for parent in [cur, *cur.parents]:
                if (parent / "Anchor.toml").exists():
                    return parent
            return None

        workspace_root = _find_anchor_root(base_dir)
        if workspace_root is None:
            # Fallback to active project if it looks like an Anchor workspace
            try:
                active = getattr(app.session_context.metadata, "active_project", None)
                if active:
                    ap = Path(active).expanduser()
                    if (ap / "Anchor.toml").exists():
                        workspace_root = ap
            except Exception:
                pass

        # Resolve template path from registry if present; otherwise fallback to templates/
        template_path = None
        try:
            entry = next((e for e in registry if e.key == key), None)
            if entry is not None and entry.template_path:
                template_path = resolve_registry_template_path(entry.template_path)
        except Exception:
            template_path = None
        if template_path is None and key not in templates:
            msg = (
                f"Blueprint '{key}' is not available locally. Available templates: {', '.join(sorted(templates)) or '(none)'}"
            )
            return CommandResponse(messages=[("system", msg)])

        if workspace_root is not None:
            # Hand off insertion to agent/CLI via /blueprint scaffold
            try:
                answers_json = json.dumps(answers or {
                    "program_name": program_name,
                    "author_pubkey": author,
                    "cluster": cluster or "devnet",
                    "program_id": program_id,
                }, separators=(",", ":"))
            except Exception:
                answers_json = "{}"
            import shlex as _shlex
            cmd_parts = [
                "/blueprint",
                "scaffold",
                "--key",
                key,
                "--target",
                str(workspace_root),
                "--workspace",
                str(workspace_root),
                "--answers-json",
                answers_json,
            ]
            if force:
                cmd_parts.append("--force")
            dispatch = " ".join(_shlex.quote(p) for p in cmd_parts)
            # Execute immediately for synchronous behavior in CLI/tests
            routed = app.command_router.dispatch(app, dispatch[1:] if dispatch.startswith("/") else dispatch)
            return routed

        # Otherwise scaffold a fresh workspace at dest
        dest = base_dir if dest is not None else (Path.cwd() / f"{program_name}-workspace")
        options = RenderOptions(
            template=key,
            destination=dest,
            program_name=program_name,
            author_pubkey=author,
            program_id=program_id,
            cluster=cluster or "devnet",
            overwrite=force,
            template_path=template_path,
        )
        # Hand off fresh scaffold to agent/CLI via /blueprint scaffold
        try:
            answers_json = json.dumps(answers or {
                "program_name": program_name,
                "author_pubkey": author,
                "cluster": cluster or "devnet",
                "program_id": program_id,
            }, separators=(",", ":"))
        except Exception:
            answers_json = "{}"
        target_dir = dest
        import shlex as _shlex
        cmd_parts = [
            "/blueprint",
            "scaffold",
            "--key",
            key,
            "--target",
            str(target_dir),
            "--answers-json",
            answers_json,
        ]
        if force:
            cmd_parts.append("--force")
        dispatch = " ".join(_shlex.quote(p) for p in cmd_parts)
        routed = app.command_router.dispatch(app, dispatch[1:] if dispatch.startswith("/") else dispatch)
        return routed

    router.register(
        SlashCommand(
            "new",
            handle,
            "Create a new blueprint: /new <key> [--dir <path>] [--program <name>] [--author <pubkey>] [--cluster <cluster>] [--program-id <id>] [--force]",
        )
    )


__all__ = ["register"]
def _decimal_to_cli_string(amount: Decimal) -> str:
    text = format(amount, "f")
    if "." in text:
        text = text.rstrip("0").rstrip(".")
    return text or "0"


def _parse_decimal(value: str | int | float | Decimal, *, field: str) -> Decimal:
    try:
        return Decimal(str(value))
    except (InvalidOperation, ValueError):
        raise ValueError(f"'{field}' must be numeric.")


def _determine_rpc_and_cluster(app: "CLIApp") -> tuple[str, str]:
    cfg_ctx = getattr(app, "config_context", None)
    cfg = getattr(cfg_ctx, "config", None)
    rpc_url = getattr(cfg, "rpc_url", "https://api.devnet.solana.com")
    cluster = getattr(cfg, "network", "devnet")
    return rpc_url, cluster


def _spl_token_quick_flow(
    app: "CLIApp",
    *,
    decimals_input: str | int | float | None,
    supply_input: str | int | float | None,
    cluster_hint: str | None,
    meta_name: str | None = None,
    meta_symbol: str | None = None,
    meta_uri: str | None = None,
    meta_royalty_bps: str | int | None = None,
    meta_creators: str | None = None,
    meta_collection: str | None = None,
    meta_run: bool = False,
) -> CommandResponse:
    if shutil.which("spl-token") is None:
        return CommandResponse(messages=[("system", "spl-token CLI not found in PATH. Install it or run `/env install spl-token`.")])

    status = app.wallet_manager.status()
    if not status.exists or not status.public_key:
        return CommandResponse(messages=[("system", "No SolCoder wallet found. Run `/wallet create` or `/wallet restore` first.")])

    # Capture balance before flow to compute spend delta
    try:
        balance_before = float(app._fetch_balance(status.public_key) or 0.0)
    except Exception:
        balance_before = 0.0

    # Parse decimals and supply
    decimals_raw = decimals_input if decimals_input is not None else 9
    try:
        decimals = int(str(decimals_raw))
    except ValueError:
        return CommandResponse(messages=[("system", "'decimals' must be an integer between 0 and 9.")])
    if decimals < 0 or decimals > 9:
        return CommandResponse(messages=[("system", "'decimals' must be between 0 and 9.")])

    supply_raw = supply_input if supply_input is not None else "0"
    try:
        supply = _parse_decimal(supply_raw, field="initial_supply")
    except ValueError as exc:
        return CommandResponse(messages=[("system", str(exc))])
    if supply < 0:
        return CommandResponse(messages=[("system", "Initial supply cannot be negative.")])

    scale = Decimal(10) ** decimals
    base_units = supply * scale
    if base_units != base_units.to_integral_value():
        return CommandResponse(messages=[("system", f"Initial supply exceeds the precision allowed by {decimals} decimals.")])

    supply_cli_str = _decimal_to_cli_string(supply)

    rpc_url, config_cluster = _determine_rpc_and_cluster(app)
    cluster = cluster_hint or config_cluster
    rpc_url = _rpc_for_cluster(cluster, app)

    summary_lines = [
        "Quick SPL token mint:",
        f"  Wallet: {status.masked_address}",
        f"  Decimals: {decimals}",
        f"  Initial supply: {supply_cli_str}",
        f"  Cluster: {cluster}",
    ]
    app.console.print(Panel.fit("\n".join(summary_lines), title="Review & Confirm", border_style="cyan"))
    app.console.print("[bold yellow]Enter wallet passphrase to continue.[/bold yellow]")
    passphrase = app._prompt_secret("Wallet passphrase", allow_master=False)
    app.console.print("[bold yellow]Type 'mint' to proceed or press Enter to cancel.[/bold yellow]")
    ack = app._prompt_text("Confirm (mint)").strip().lower()
    if ack != "mint":
        return CommandResponse(messages=[("system", "Cancelled.")])

    try:
        secret = app.wallet_manager.export_wallet(passphrase)
    except Exception as exc:  # noqa: BLE001
        return CommandResponse(messages=[("system", f"Failed to export wallet: {exc}")])

    key_path: Path | None = None
    try:
        handle = tempfile.NamedTemporaryFile("w", delete=False, suffix=".json")
        with handle:
            handle.write(secret)
            handle.flush()
            key_path = Path(handle.name)
        try:
            os.chmod(key_path, 0o600)
        except PermissionError:
            pass

        # Basic base58 validation helpers
        _B58 = set("123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz")

        def _looks_like_pubkey(value: str) -> bool:
            v = value.strip()
            return 32 <= len(v) <= 64 and all(c in _B58 for c in v)

        def _extract_pubkey_from_text(text: str) -> str | None:
            for token in text.replace(",", " ").split():
                if _looks_like_pubkey(token):
                    return token
            return None

        def _run_cmd(args: list[str]) -> subprocess.CompletedProcess[str]:
            result = subprocess.run(
                args,
                capture_output=True,
                text=True,
                check=False,
            )
            return result

        def _extract_from_json(stdout: str) -> dict[str, str]:
            out: dict[str, str] = {}
            try:
                data = json.loads(stdout)
            except Exception:
                return out

            def _walk(node: object) -> None:
                if isinstance(node, dict):
                    for k, v in node.items():
                        if isinstance(v, (str, int, float)):
                            sval = str(v)
                            kl = str(k).lower()
                            if kl in {"signature", "tx", "transaction", "sig"}:
                                out.setdefault("signature", sval)
                            if kl in {"address", "mint", "token", "account", "ata", "associatedtokenaddress"}:
                                out.setdefault(kl, sval)
                        else:
                            _walk(v)
                elif isinstance(node, list):
                    for it in node:
                        _walk(it)

            _walk(data)
            return out

        def _parse_created_address(stdout: str, keyword: str) -> str | None:
            # Prefer JSON when available
            meta = _extract_from_json(stdout)
            for key in ("mint", "token", "address"):
                if meta.get(key):
                    return meta[key]
            # Fallback to text parsing
            lower_kw = keyword.lower()
            for line in stdout.splitlines():
                text = line.strip()
                if text.lower().startswith(f"creating {lower_kw}"):
                    # Try to extract a plausible base58 public key
                    candidate = _extract_pubkey_from_text(text)
                    if candidate:
                        return candidate
            return None

        def _parse_signature(stdout: str) -> str | None:
            meta = _extract_from_json(stdout)
            if meta.get("signature"):
                return meta["signature"]
            for line in stdout.splitlines():
                if "Signature" in line:
                    return line.split(":", 1)[-1].strip()
            return None

        # 1) Create mint
        create_token_cmd = [
            "spl-token",
            "create-token",
            "--decimals",
            str(decimals),
            "--fee-payer",
            str(key_path),
            "--mint-authority",
            status.public_key,
            "--enable-metadata",
        ]
        create_token_cmd.extend(TOKEN_2022_PROGRAM_ARGS)
        create_token_cmd.extend(
            [
                "--output",
                "json",
                "--url",
                rpc_url,
            ]
        )
        with app.console.status("Creating token mint (Token-2022)…", spinner="dots"):
            create_result = _run_cmd(create_token_cmd)
        if create_result.returncode != 0:
            err = create_result.stderr.strip() or create_result.stdout.strip() or "spl-token create-token failed."
            return CommandResponse(messages=[("system", err)])
        mint_address = _parse_created_address(create_result.stdout, "token")
        mint_signature = _parse_signature(create_result.stdout)

        if not mint_address:
            return CommandResponse(messages=[("system", "Unable to determine mint address from spl-token output.")])

        # 2) Create associated token account for wallet
        create_account_cmd = [
            "spl-token",
            "create-account",
            mint_address,
            "--owner",
            status.public_key,
            "--fee-payer",
            str(key_path),
        ]
        create_account_cmd.extend(TOKEN_2022_PROGRAM_ARGS)
        create_account_cmd.extend(
            [
                "--output",
                "json",
                "--url",
                rpc_url,
            ]
        )
        with app.console.status("Creating associated token account…", spinner="dots"):
            account_result = _run_cmd(create_account_cmd)
        if account_result.returncode != 0:
            err = account_result.stderr.strip() or account_result.stdout.strip() or "spl-token create-account failed."
            return CommandResponse(messages=[("system", err)])
        account_address = _parse_created_address(account_result.stdout, "account")
        account_signature = _parse_signature(account_result.stdout)
        if not account_address:
            # Fallback: compute ATA deterministically via spl-token address
            addr_cmd = [
                "spl-token",
                "address",
                "--verbose",
                "--token",
                mint_address,
                "--owner",
                status.public_key,
            ]
            addr_cmd.extend(TOKEN_2022_PROGRAM_ARGS)
            addr_cmd.extend(
                [
                    "--url",
                    rpc_url,
                ]
            )
            addr_result = _run_cmd(addr_cmd)
            if addr_result.returncode == 0:
                meta = _extract_from_json(addr_result.stdout)
                account_address = meta.get("address") or meta.get("ata") or meta.get("account")
                if not account_address:
                    # treat stdout as a bare address
                    lines = [ln.strip() for ln in addr_result.stdout.splitlines() if ln.strip()]
                    # Prefer explicit "Associated token address:" line when present
                    for ln in lines:
                        if "associated token address" in ln.lower():
                            cand = _extract_pubkey_from_text(ln)
                            if cand:
                                account_address = cand
                                break
                    # Otherwise pick the last base58-looking token in the output
                    if not account_address:
                        candidates: list[str] = []
                        for ln in lines:
                            cand = _extract_pubkey_from_text(ln)
                            if cand:
                                candidates.append(cand)
                        if candidates:
                            # avoid picking the wallet address if that's included first
                            for cand in reversed(candidates):
                                if cand != (status.public_key or ""):
                                    account_address = cand
                                    break
        if not account_address:
            # Surface the mint address so the user can proceed manually if needed
            explorer = f"https://explorer.solana.com/address/{mint_address}"
            if cluster and cluster not in {"mainnet", "mainnet-beta"}:
                explorer = f"{explorer}?cluster={cluster}"
            hint_lines = [
                "Unable to determine associated token account address from spl-token output.",
                f"Mint (created): {mint_address}",
                f"Explorer: {explorer}",
                "You can fetch the ATA and retry mint manually:",
                (
                    "  spl-token address --verbose "
                    f"--token {mint_address} --owner {status.public_key} "
                    f"--program-id {TOKEN_2022_PROGRAM_ID} -u {rpc_url}"
                ),
            ]
            return CommandResponse(messages=[("system", "\n".join(hint_lines))])

        mint_tx_signature: str | None = None
        minted_amount_display: str | None = None
        if supply > 0:
            minted_amount_display = supply_cli_str
            mint_cmd = [
                "spl-token",
                "mint",
                mint_address,
                supply_cli_str,
                "--mint-authority",
                str(key_path),
                "--fee-payer",
                str(key_path),
            ]
            mint_cmd.extend(TOKEN_2022_PROGRAM_ARGS)
            mint_cmd.extend(
                [
                    "--output",
                    "json",
                    "--url",
                    rpc_url,
                ]
            )
            mint_cmd.append(account_address)
            with app.console.status("Minting initial supply…", spinner="dots"):
                mint_result = _run_cmd(mint_cmd)
            if mint_result.returncode != 0:
                err = mint_result.stderr.strip() or mint_result.stdout.strip() or "spl-token mint failed."
                return CommandResponse(messages=[("system", err)])
            mint_tx_signature = _parse_signature(mint_result.stdout)

    finally:
        try:
            if key_path:
                key_path.unlink(missing_ok=True)
        except Exception:
            pass

    explorer = f"https://explorer.solana.com/address/{mint_address}"
    if cluster and cluster not in {"mainnet", "mainnet-beta"}:
        explorer = f"{explorer}?cluster={cluster}"

    lines = [
        "✅ Quick SPL token created.",
        f"Mint: {mint_address}",
    ]
    if mint_signature:
        lines.append(f"Mint signature: {mint_signature}")
    if account_address:
        detail = f"Wallet ATA: {account_address}"
        if account_signature:
            detail += f" (signature: {account_signature})"
        lines.append(detail)
    if mint_tx_signature and minted_amount_display:
        lines.append(f"Minted {minted_amount_display} tokens (signature: {mint_tx_signature})")
    lines.append(f"Explorer: {explorer}")

    # Update wallet balance and session spend based on observed delta
    try:
        status_after = app.wallet_manager.status()
        balance_after = float(app._fetch_balance(status_after.public_key) or 0.0)
        delta = max(0.0, balance_before - balance_after)
        metadata = app.session_context.metadata
        try:
            metadata.spend_amount = float(getattr(metadata, "spend_amount", 0.0) or 0.0) + float(delta)
        except Exception:
            pass
        app._update_wallet_metadata(status_after, balance=balance_after)
        if delta > 0:
            lines.append(f"Fees spent: {delta:.5f} SOL")
            lines.append(f"Wallet balance: {balance_after:.3f} SOL")
    except Exception:
        pass

    summary_text = "\n".join(lines)
    app.console.print(Panel.fit(summary_text, title="Quick Token Result", border_style="green"))

    app.log_event("token", f"Quick SPL token created: {mint_address}")
    # If metadata parameters were provided, set metadata directly; otherwise launch wizard
    import shlex as _shlex
    if meta_name and meta_symbol and meta_uri:
        md_cmd = [
            "/metadata",
            "set",
            "--mint",
            str(mint_address),
            "--name",
            meta_name,
            "--symbol",
            meta_symbol,
            "--uri",
            meta_uri,
        ]
        if meta_royalty_bps is not None and str(meta_royalty_bps).strip() != "":
            md_cmd += ["--royalty-bps", str(meta_royalty_bps)]
        if meta_creators:
            md_cmd += ["--creators", meta_creators]
        if meta_collection:
            md_cmd += ["--collection", meta_collection]
        if meta_run:
            md_cmd += ["--run"]
    else:
        md_cmd = [
            "/metadata",
            "wizard",
            "--mint",
            str(mint_address),
            "--type",
            "token",
        ]
        if meta_name:
            md_cmd += ["--default-name", meta_name]
        if meta_symbol:
            md_cmd += ["--default-symbol", meta_symbol]
        if meta_uri:
            md_cmd += ["--default-uri", meta_uri]
        if meta_royalty_bps is not None and str(meta_royalty_bps).strip() != "":
            md_cmd += ["--default-royalty-bps", str(meta_royalty_bps)]
        if meta_creators:
            md_cmd += ["--default-creators", meta_creators]
        if meta_collection:
            md_cmd += ["--default-collection", meta_collection]
    # Show success then dispatch metadata command
    dispatch = " ".join(_shlex.quote(p) for p in md_cmd)
    try:
        routed = app.command_router.dispatch(app, dispatch[1:] if dispatch.startswith("/") else dispatch)
        if routed.messages:
            routed.messages.insert(0, ("system", summary_text))
            return routed
        return CommandResponse(messages=[("system", summary_text)])
    except Exception:
        return CommandResponse(messages=[("system", summary_text)])
